name: Release
on:
    workflow_dispatch:
    push:
        branches: ['main']
jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
        steps:
            - name: Checkout code
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

            - name: Set up uv
              uses: astral-sh/setup-uv@05273c154d09957eb9a2377d9c988fbda431d1c5 # v6.4.0
              with:
                version: "latest"
      
            - name: Release
              run: |
                uv build
                uv publish --publish-url https://test.pypi.org/legacy/ --trusted-publishing always
